apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: ClusterIP
  ports:
    - name: rethinkdb
      protocol: TCP
      port: 28015
      targetPort: 28015
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
