apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      volumes:
        - name: data
          {{- if .Values.persistence.hostPath }}
          hostPath:
            path: {{ .Values.persistence.hostPath }}
          {{- end }}
          {{- if .Values.persistence.awsElasticBlockStoreVolumeID }}
          awsElasticBlockStore:
            volumeID: {{ .Values.persistence.awsElasticBlockStoreVolumeID }}
            fsType: ext4
          {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: rethinkdb:2.3
        imagePullPolicy: Always
        ports:
        - containerPort: 28015
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        volumeMounts:
        - name: data
          mountPath: /data
        # resources:
