rules:
  "no-unused-vars": 0
  "comma-dangle": 0
  "no-var": 2
  "no-cond-assign": [2, "always"]
  "dot-location": [2, "property"]
  "eqeqeq": 2
  "indent": [2, 2]
  "quotes": [2, "double"]
  "linebreak-style": [2, "unix"]
  "semi": [2, "always"]
  "no-eval": 2
env:
  es6: true
  node: true
  browser: true
extends: 'eslint:recommended'
globals:
  it: true
  describe: true
ecmaFeatures:
  modules: true
  jsx: true
  experimentalObjectRestSpread: true
plugins:
  - react
