rules:
  "no-unused-vars": 0
  "comma-dangle": 0
  indent:
    - 2
    - 2
  quotes:
    - 2
    - double
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
env:
  es6: true
  node: true
  browser: true
extends: 'eslint:recommended'
ecmaFeatures:
  modules: true
  jsx: true
  experimentalObjectRestSpread: true
plugins:
  - react
