parser: babel-eslint
plugins:
  - react
  - prettier
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
rules:
  prettier/prettier: "error"
  "no-unused-vars": 0
  "comma-dangle": 0
  "no-var": 2
  "no-cond-assign": [2, "always"]
  "dot-location": [2, "property"]
  "eqeqeq": 2
  "indent": [2, 2, { "SwitchCase": 1 }]
  "linebreak-style": [2, "unix"]
  "no-eval": 2
env:
  es6: true
  node: true
  browser: true
globals:
  it: true
  describe: true
  beforeEach: true
  afterEach: true
  expect: true
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
