
# We don't wanna double-build version tags
branches:
  except:
    - /^v[0-9]/

language: node_js

node_js:
  - "6"

services:
  - docker

before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

script:
  - run/ci-build.sh
