
# URL of the Bellamie API server, used for SK services.
API_SERVER_URL: "http://localhost:8100"

# URL of the Bellamie API server, used for public React apps. The same if you're developing
# locally, different if you're not.
PUBLIC_API_SERVER_URL: "http://localhost:8100"

# Base URL of the Gort user interface. This lets you run it at subdirectories, like "app".
PUBLIC_GORT_BASE_PATH: "/"

# Path for applications to get at the Shoko RTMP server from inside the application.
RTMP_URL_INTERNAL: "rtmp://localhost/stream/"

# Path for external users to get at the Shoko RTMP server for the preview stream.
RTMP_URL_EXTERNAL: "rtmp://localhost/stream/"

# These are API credentials for S3 for the FileOutputVertex. Also other things, eventually.
AWS_ACCESS_KEY_ID: "xxxxxxxxxxxxxxxxxxxx"
AWS_SECRET_ACCESS_KEY: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
AWS_USER_UPLOAD_BUCKET: "yourbucket"
AWS_USER_UPLOAD_REGION: "us-east-1"
AWS_USER_UPLOAD_PREFIX: "/myfiles"

# Port on which the Bellamie server oughta run.
BELLAMIE_PORT: 8100

# Where's your Rethink database?
RETHINK_HOST: "localhost"
RETHINK_PORT: 28015
RETHINK_DATABASE: dev
