version: "2"
services:

  rethink:
    image: rethinkdb:2.2
    volumes:
      - ./config.dockercompose.yml:/config.yml
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./rethinkdb_data:/data/rethinkdb_data
      - ./config.dockercompose.yml:/config.yml

  shoko:
    image: streamkitchen/shoko:latest
    depends_on:
     - rethink
    volumes:
      - ./config.dockercompose.yml:/config.yml
    restart: always
    ports:
      - "1935:1935"

  bellamie:
    depends_on:
      - rethink
      - shoko
    image: streamkitchen/bellamie:latest
    links:
      - rethink
    ports:
      - "8100:80"
    volumes:
      - ./config.dockercompose.yml:/config.yml
    restart: always

  pipeland:
    depends_on:
      - shoko
      - bellamie
    links:
      - shoko
      - bellamie
    image: streamkitchen/pipeland:latest
    restart: always
    volumes:
      - ./config.dockercompose.yml:/config.yml

  gort:
    volumes:
      - ./config.dockercompose.yml:/config.yml
    depends_on:
      - bellamie
    image: streamkitchen/gort:latest
    restart: always
    ports:
      - "5000:80"
