version: "2"
services:

  rethink:
    image: rethinkdb:2.2
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./rethinkdb_data:/data/rethinkdb_data

  shoko:
    image: streamkitchen/shoko:latest
    depends_on:
     - rethink
    restart: always
    ports:
      - "1935:1935"

  bellamie:
    depends_on:
      - rethink
      - shoko
    image: streamkitchen/bellamie:latest
    links:
      - rethink
    ports:
      - "8100:80"
    restart: always
    environment:
      - SK_RETHINK_HOST=rethink
      - SK_RETHINK_PORT=28015
      - SK_RETHINK_DATABASE=dev
      - SK_BELLAMIE_PORT=80

  pipeland:
    depends_on:
      - shoko
      - bellamie
    links:
      - shoko
      - bellamie
    image: streamkitchen/pipeland:latest
    restart: always
    environment:
      - SK_API_SERVER_URL=http://bellamie
      - SK_PUBLIC_RTMP_URL_PREVIEW=rtmp://localhost/stream/
      - SK_RTMP_URL_INTERNAL=rtmp://shoko/stream/

  gort:
    depends_on:
      - bellamie
    image: streamkitchen/gort:latest
    restart: always
    ports:
      - "5000:80"
    environment:
      - SK_PUBLIC_API_SERVER_URL=http://localhost:8100
      - SK_PUBLIC_RTMP_URL_PREVIEW=rtmp://localhost/stream/
      - SK_RTMP_URL_INTERNAL=rtmp://shoko/stream/
      - SK_PUBLIC_GORT_BASE_PATH=/
