
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
data:
  client-header-buffer-size: 16k
  large-client-header-buffers: "12 16k"
  ssl-buffer-size: 16k
  use-http2: "false"
  {{- if .Values.global.development }}
  log-format-upstream: '$request_method $uri $status [$proxy_upstream_name]'
  {{- end }}
