apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: nginx
        image: "gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.2"
        imagePullPolicy: Always
        command:
          - /nginx-ingress-controller
        args:
          - --default-backend-service
          - {{ .Release.Namespace }}/{{ .Release.Name }}-sp-default
          - --configmap={{ .Release.Namespace }}/{{ template "fullname" . }}
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
          - containerPort: 80
            {{- if .Values.global.development }}
            hostPort: 80
            {{- end }}
          - containerPort: 443
            {{- if .Values.global.development }}
            hostPort: 443
            {{- end }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 1
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
