
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/proxy-buffer-size: 12k
spec:
  tls:
  - secretName: {{ .Values.global.domain }}
    hosts:
    - {{ .Values.global.domain }}
  rules:
  - host: {{ .Values.global.domain }}
    http:
      paths:
      - path: /api
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 80
