apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  # modify this to specify your address
  lego.email: "{{ .Values.global.adminEmail }}"
  # configure letencrypt's production api
  lego.url: "{{ .Values.acmeUrl }}"
