{{- if .Values.enabled }}
{{- $domain := .Values.global.loginUrl | split "/" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: {{ $domain._2 }}
    hosts:
    - {{ $domain._2 }}
  rules:
  - host: {{ $domain._2 }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 80
  - host: {{ $domain._2 }}
    http:
      paths:
      - path: /schema.json
        backend:
          serviceName: {{ .Release.Name }}-sp-schema
          servicePort: 80
{{- end }}
