# Default values for ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  development: false
  serviceType: ClusterIP

# This is one generated just for SP stuff, which is superior to using the default nginx one. Even
# better, generate your own and put it here!
dhParam: |-
  -----BEGIN DH PARAMETERS-----
  MIICCAKCAgEAm9TWE06lwIdsz2IVaoKKOHCJBWOMHWWZOSW/qa396yb+PwFzG4US
  QGtnA0M4Lw7HGXM/+vUAUrahF/7gcarAurq52xh1Rm5wfy5e0BVfHnxCH3Pnx9xE
  Xb6Q8eDR0ozLwznRJai2K5vX6KCGHwUKGGGP3wDfLniuZnhMAQ3ZrJOF7SAgI/9f
  d+Xa1YSwycU0H5L5Bh3XaGey1sq0hOyzne/IWxXm0HJen22gnNZvBLSHYX+FsMPp
  i7PXPTKK6+5xP907kDWg8uF3tsajtLblLfz/Dysd1daRN76v2X4f2kCMTAaRt9xs
  8Tx5zCan6pX05EfYVdlGH720KoFYmKnias/q3eWtZrLwaS3zbv7/tzqWwBYB/oTY
  RF6cff06+u1Pr/n/PG4v/hFu8M/PKnLA1XIAPdbSsyRZwqakXOaHSYroV1m6ghpv
  Cqhdfm87TuD3haqnq0P3sPMOh8XwBIvqr5J7eVuVoWyNWkOZr0UzH+MugI8nAr1d
  zck1/TQr/gcKQKa4M2w1dkqHQ2hXUygn+tTflJWiVymXYbv1ep/Wwdc5MDN8mkm8
  GEBvOaCFKgnyzQlhSqyLmsFDMwLQOODpiSyANNIGDkNplhyPMFKOpKvXEdEvgF8C
  UaW1wKvVqrg9Y8tVbyHdAh9b2oy6wu4TDTv+rXBQKksz/f9+/bsJr/MCAQI=
  -----END DH PARAMETERS-----
