apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-video
  namespace: default
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: demo-video
    spec:
      containers:
        - name: nginx
          image: "streamplace/demo-video"

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-video
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - secretName: cdn.stream.place
    hosts:
    - cdn.stream.place
  rules:
  - host: cdn.stream.place
    http:
      paths:
      - path: /demo-video
        backend:
          serviceName: demo-video
          servicePort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: demo-video
spec:
  type: ClusterIP
  selector:
    app: demo-video
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
