{{ $root := . }}
{{ range .Values.global.plugins }}
{{- if eq . $root.Chart.Name }}
{{- with $root }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  annotations:
    stream.place/sp-schema: "true"
    stream.place/sp-plugin: "{{ .Chart.Name }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
{{- $files := .Files }}
{{- range $path, $bytes := .Files.Glob "schema/**.yaml" }}
  {{- $name := base $path | split "."}}
  {{ $name._0 }}: |
{{ $files.Get $path | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
