# Default values for streamkitchen.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  domain: streamkitchen.example.com
  adminEmail: admin@example.com
  repo: docker.io/streamkitchen
  version: latest

rethinkdb:
  persistence:
    hostPath: /home/root/code/streamkitchen/data/rethink
