apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logspout
spec:
  template:
    metadata:
      labels:
        app: logspout
    spec:
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      containers:
      - image: gliderlabs/logspout
        name: logspout
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock

---

apiVersion: v1
kind: Service
metadata:
  name: logspout
spec:
  selector:
    app: logspout
  type: NodePort
  ports:
    - name: logspout
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
