apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ubuntu
spec:
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      hostNetwork: false
      containers:
        - name: ubuntu
          image: ubuntu:xenial
          command:
            - tail
            - -f
            - /dev/null

