{{- if .Values.enabled }}
{{- $parent := . -}}
{{- $domain := .Values.domain -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" $parent }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  {{- if .Values.global.development }}
  - secretName: {{ .Values.global.domain }}
    hosts:
    - {{ .Values.global.domain }}
  rules:
  - host: {{ .Values.global.domain }}
    http:
      paths:
      - path: /sp-dev-certs
        backend:
          serviceName: {{ template "fullname" $parent }}
          servicePort: 80
  {{- else }}
  - secretName: {{ $domain }}
    hosts:
    - {{ $domain }}
  {{- range .Values.developers }}
  - secretName: {{ .username }}.{{ $domain }}
    hosts:
    - {{ .username }}.{{ $domain }}
  {{- end }}
  rules:
  - host: {{ $domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" $parent }}
          servicePort: 80
  {{- range .Values.developers }}
  - host: {{ .username }}.{{ $domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" $parent }}
          servicePort: 80
  {{- end }}
  {{- end }}
{{- end }}
