apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      hostNetwork: true
      volumes:
      - name: coturn-command
        configMap:
          name: {{ template "fullname" . }}
      containers:
        - name: "coturn"
          image: ianblenke/coturn:latest
          command:
            - /bin/sh
          args:
            - "/coturn.sh"
          volumeMounts:
          - name: coturn-command
            mountPath: /coturn.sh
            subPath: coturn.sh
