dependencies:
  - name: sp-rethinkdb
    version: 0.0.6
    repository: 'https://charts.stream.place'
  - name: sp-logs
    version: 0.0.6
    repository: 'https://charts.stream.place'
  - name: sp-plugin-core
    version: 0.0.6
    repository: 'https://charts.stream.place'
  - name: sp-schema
    version: 0.0.6
    repository: 'https://charts.stream.place'

