apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
      containers:
        - name: logspout
          imagePullPolicy: Always
          image: gliderlabs/logspout:latest
          {{- if .Values.logServer }}
          args:
            - {{ .Values.logServer }}
          {{- end }}
          volumeMounts:
            - name: dockersock
              mountPath: /var/run/docker.sock
