apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ if .Values.global.development }}NodePort{{ else }}ClusterIP{{end}}
  selector:
    app: {{ template "fullname" . }}
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    {{- if .Values.global.development }}
    nodePort: 30400
    {{- end }}
    name: http
